create table
  public.album (
    id integer generated by default as identity,
    album_name text null,
    artist_id text null,
    genre text null,
    explicit_rating integer null,
    label text null,
    release_date date null,
    added_date timestamp with time zone not null default now(),
    constraint album_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.artist (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    artist_name text null,
    constraint artist_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.explicit_submissions (
    id bigint generated by default as identity,
    songid integer null,
    exbool integer null default 0,
    constraint explicit_submissions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.song (
    song_id integer generated by default as identity,
    artist_id integer null,
    created_at timestamp with time zone not null default now(),
    song_name text null,
    featured_artist text null,
    explicit_rating integer null,
    length integer null,
    constraint song_pkey primary key (song_id)
  ) tablespace pg_default;

create table
  public.song_playlist (
    user_id bigint not null,
    playlist_id bigint not null,
    song_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint song_playlist_pkey primary key (user_id)
  ) tablespace pg_default;

create table
  public.streams (
    stream_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    user_id integer null,
    song_id integer null,
    constraint streams_pkey primary key (stream_id)
  ) tablespace pg_default;

create table
  public.user_playlist (
    playlist_id bigint generated by default as identity,
    playlist_name text null default ''::text,
    created_at timestamp with time zone not null default now(),
    user_id bigint null,
    constraint user_playlist_pkey primary key (playlist_id)
  ) tablespace pg_default;

create table
  public.users (
    user_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    username text null,
    constraint users_pkey primary key (user_id)
  ) tablespace pg_default;  